config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "events#index"
  resources :events, only: [:new, :create, :index, :show]
  resources :attendee_events, only: [:create]
  resources :users, only: [:show]
  # get "/users/:id", to: "users#show"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attendee_event.rb
class AttendeeEvent < ApplicationRecord
  belongs_to :attendee, class_name: "User"

  # Doesn't work with:
  # belongs_to :attended_event, class_name: "Event"
  # shows error of: {"attended_event"=>["must exist"]}
  belongs_to :event_attended, class_name: "Event"

  # need to enforce uniqueness of attendee_id and event_attended_id
  
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :attendee_events, foreign_key: :event_attended_id
  has_many :attendees, through: :attendee_events, source: :attendee

  belongs_to :creator, class_name: "User"

  scope :past, -> { where("date < ?", Date.today) }
  scope :future, -> { where("date >= ?", Date.today) }

  # def self.past 
  #   Event.where("date < ?", Date.today)
  # end

  # def self.future 
  #   Event.where("date >= ?", Date.today)
  # end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :attendee_events, foreign_key: :attendee_id
  has_many :attended_events, through: :attendee_events, source: :event_attended

  has_many :created_events, foreign_key: :creator_id, class_name: "Event"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/attendee_events_controller.rb
class AttendeeEventsController < ApplicationController
  
  def create
    attendee_event = AttendeeEvent.new(attendee_id: params[:attendee_id], 
                                        event_attended_id: params[:event_attended_id])
    # if attendee_event.save
    #   flash[:notice] = "Successfully joined the event."
    #   redirect_back fallback_location: root_path
    # else
    #   flash[:alert] = "Failed to join the event."
    #   flash[:error] = attendee_event.errors
    #   redirect_back fallback_location: root_path
    # end

    begin
      attendee_event.save
      flash[:notice] = "Successfully joined the event."
      redirect_back fallback_location: root_path
    rescue ActiveRecord::RecordNotUnique => e
      flash[:alert] = "You have already joined that event."
      redirect_back fallback_location: root_path
    end
  end

  private

  # def attendee_event_params
  #   params.require(:)
  # end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.created_events.build(event_params)
    if @event.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    # should this be using event_params?
    @event = Event.find(params[:id])
  end

  private

  def event_params
    params.require(:event).permit(:name, :venue, :date)
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :authenticate_user!, only: [:show]

  def show
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show]

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendee_event_helper.rb
module AttendeeEventHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/events/index.html.erb
<div class="index">
    <h1>Home</h1>
    <hr>
    <% if user_signed_in? %>
        <%= link_to new_event_path do%>
            <div class="new-event"> 
                <span>New Event</span>
                <svg style="width:24px;height:24px" viewBox="0 0 24 24">
                    <path fill="currentColor" d="M19,13H13V19H11V13H5V11H11V5H13V11H19V13Z" />
                </svg>
            </div>
        <% end %>
    <% else %>
        <div class="new-event">
            <p> Log in to create an event. </p>
        </div>
    <% end %>

    <h2>Future Events:</h2>
    <hr>
    <% Event.future.each do |event| %>
        <div class="event-card">
            <%= link_to event do %>
                <p><%= event.name %></p>
            <% end %>
            <p><span>venue:</span> <%= event.venue %></p>
            <p><span>date:</span> <%= event.date %></p>

            <% if user_signed_in? %>
                <!-- <%= button_to "Join", attendee_events_path(attendee_id: current_user.id, event_attended_id: event.id) %> -->
                <%= button_to attendee_events_path(attendee_id: current_user.id, event_attended_id: event.id) do %>
                    <svg style="width:24px;height:24px" viewBox="0 0 24 24">
                        <path fill="currentColor" d="M15,14C12.33,14 7,15.33 7,18V20H23V18C23,15.33 17.67,14 15,14M6,10V7H4V10H1V12H4V15H6V12H9V10M15,12A4,4 0 0,0 19,8A4,4 0 0,0 15,4A4,4 0 0,0 11,8A4,4 0 0,0 15,12Z" />
                    </svg>
                <% end %>
            <% else %>
                <div>log in to join an event.</div>
            <% end %>
        </div>
    <% end %>

    <h2>Past Events:</h2>
    <hr>
    <% Event.past.each do |event| %>
        <div class="event-card">
            <%= link_to event do %>
                <p><%= event.name %></p>
            <% end %>
            <p><span>venue:</span> <%= event.venue %></p>
            <p><span>date:</span> <%= event.date %></p>

            <% if user_signed_in? %>
                <!-- <%= button_to "Join", attendee_events_path(attendee_id: current_user.id, event_attended_id: event.id) %> -->
                <%= button_to attendee_events_path(attendee_id: current_user.id, event_attended_id: event.id) do %>
                    <svg style="width:24px;height:24px" viewBox="0 0 24 24">
                        <path fill="currentColor" d="M15,14C12.33,14 7,15.33 7,18V20H23V18C23,15.33 17.67,14 15,14M6,10V7H4V10H1V12H4V15H6V12H9V10M15,12A4,4 0 0,0 19,8A4,4 0 0,0 15,4A4,4 0 0,0 11,8A4,4 0 0,0 15,12Z" />
                    </svg>
                <% end %>
            <% else %>
                <div>log in to join an event.</div>
            <% end %>
        </div>
    <% end %>
</div>

app/views/events/new.html.erb
<%= form_with model: @event do |form| %>
    <%= form.label :name %>
    <%= form.text_field :name %>
    <%= form.label :venue %>
    <%= form.text_field :venue %>
    <%= form.label :date %>
    <%= form.date_field :date %>
    <%= form.submit%>
<% end %>

app/views/events/show.html.erb
<div class="event-card">
    <p><%= @event.name %></p>
    <p><%= @event.venue %></p>
    <p><%= @event.date %></p>
</div>

<h1> Attendees </h1>
<hr>

<% @event.attendees.each do |attendee| %>
    <p> <%= attendee.username %> </p>
<% end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <!-- <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p> -->

    <% flash.each do |name, message| %>
      <div class="<%= name %>"><%= message %></div>
    <% end %>

    <div class="navbar">
      <%= link_to "Private Events", root_path %>
      <div class="right">
        <% if user_signed_in? %>
          <%= link_to current_user.username, current_user %>

          <%= button_to destroy_user_session_path do %>
            <p>Log Out </p>
          <% end %>
        <% else %>
          <%= button_to new_user_session_path do %>
            <p>Log In </p>
          <% end %>

          <%= button_to new_user_registration_path do %>
            <p>Sign Up </p>
          <% end %>
        <% end %>
      
      </div>
    </div>
    
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<div class="show">
    <h1>Events you created:</h1>
    <% current_user.created_events.each do |event|  %>
        <div class="event-card">
            <p><%= event.name %></p>
            <p><%= event.venue %></p>
            <p><%= event.date %></p>
        </div>
    <% end %>

    <h1>Events you will attend:</h1>
    <% current_user.attended_events.where("date >= ?", Date.today).each do |event|  %>
        <div class="event-card">
            <p><%= event.name %></p>
            <p><%= event.venue %></p>
            <p><%= event.date %></p>
        </div>
    <% end %>

     <h1>Events you attended:</h1>
    <% current_user.attended_events.where("date < ?", Date.today).each do |event|  %>
        <div class="event-card">
            <p><%= event.name %></p>
            <p><%= event.venue %></p>
            <p><%= event.date %></p>
        </div>
    <% end %>
</div>